<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5e133c53c9d3d',
	'title' => 'Map Settings',
	'fields' => array(
		array(
			'key' => 'field_5e1371f5191ab',
			'label' => 'Γενικές Ρυθμίσεις',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e145499c0387',
			'label' => 'Airports',
			'name' => 'airports',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5e136e28003d4',
			'label' => 'Tiles',
			'name' => 'tiles',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'acfe_permissions' => '',
			'choices' => array(
				'tileurl=https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png subdomains=abcd' => 'Wikimedia Maps',
				'tileurl=https://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg subdomains=abcd' => 'Stamen Watercolor',
				'tileurl=http://tiles.wmflabs.org/hillshading/{z}/{x}/{y}.png subdomains=abcd' => 'wmflabs Hillshading',
				'tileurl=https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png subdomains=abcd' => 'Carto Light',
				'tileurl=https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png subdomains=abcd' => 'Carto Dark',
				'tileurl=http://a.tile.stamen.com/toner/{z}/{x}/{y}.png subdomains=abcd' => 'Stamen Toner',
				'tileurl=http://a.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png subdomains=abcd' => 'Humanitarian map style',
				'tileurl=http://tile.thunderforest.com/cycle/{z}/{x}/{y}.png subdomains=abcd' => 'OpenCycleMap',
				'tileurl=https://tiles.wmflabs.org/hikebike/{z}/{x}/{y}.png subdomains=abcd' => 'wmflabs Hike & Bike',
				'tileurl=http://maps.openweathermap.org/maps/2.0/weather/TA2/{z}/{x}/{y}?appid=993162d7e75e9cfcaac84ac3b5c5f11b' => 'Air temperature',
			),
			'default_value' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'placeholder' => '',
			'ajax' => 0,
		),
		array(
			'key' => 'field_5e133d354489b',
			'label' => 'FitBounds',
			'name' => 'fitbounds',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5e133c9f0b3a9',
			'label' => 'Staring Zoom',
			'name' => 'zoom',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e133d354489b',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 7,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => 18,
			'step' => 1,
		),
		array(
			'center_lat' => 38.5223841,
			'center_lng' => 24.0353394,
			'zoom' => 8,
			'key' => 'field_5e133f47ac1c0',
			'label' => 'Map Center',
			'name' => 'map_center',
			'type' => 'open_street_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e133d354489b',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'raw',
			'layers' => array(
				0 => 'OpenStreetMap',
			),
			'allow_map_layers' => 0,
			'height' => 400,
			'max_markers' => 1,
		),
		array(
			'key' => 'field_5e137207191ac',
			'label' => 'Περιφέρειες',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e1371c1191aa',
			'label' => 'Π. ΑΝΑΤΟΛΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ - ΘΡΑΚΗΣ',
			'name' => 'pamth',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5e144be66e9c5',
			'label' => 'Π. ΑΤΤΙΚΗΣ',
			'name' => 'patt',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5e24350bc5195',
			'label' => 'Π. ΒΟΡΕΙΟΥ ΑΙΓΑΙΟΥ',
			'name' => 'pba',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5e243521c5196',
			'label' => 'Π. ΔΥΤΙΚΗΣ ΕΛΛΑΔΑΣ',
			'name' => 'pde',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5e24358285d3a',
			'label' => 'Π. ΗΠΕΙΡΟΥ',
			'name' => 'php',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5e24359285d3b',
			'label' => 'Π. ΔΥΤΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ',
			'name' => 'pdm',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5e2435a485d3c',
			'label' => 'Π. ΙΟΝΙΩΝ ΝΗΣΩΝ',
			'name' => 'pin',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5e2435b085d3d',
			'label' => 'Π. ΚΕΝΤΡΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ',
			'name' => 'pkm',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5e24360e12c38',
			'label' => 'Π. ΚΡΗΤΗΣ',
			'name' => 'pkr',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5e24361f12c39',
			'label' => 'Π. ΝΟΤΙΟΥ ΑΙΓΑΙΟΥ',
			'name' => 'pne',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5e24362d12c3a',
			'label' => 'Π. ΠΕΛΟΠΟΝΝΗΣΟΥ',
			'name' => 'ppl',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5e24363a12c3b',
			'label' => 'Π. ΣΤΕΡΕΑΣ ΕΛΛΑΔΑΣ',
			'name' => 'pste',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5e24364b12c3c',
			'label' => 'Π. ΘΕΣΣΑΛΙΑΣ',
			'name' => 'pth',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5e24333a44302',
			),
			'display' => 'group',
			'layout' => 'table',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-map',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1580391368,
));

endif;