<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5e27204103e5b',
	'title' => 'App Settings',
	'fields' => array(
		array(
			'key' => 'field_5e2b19b814db6',
			'label' => 'App Content Maximum Width',
			'name' => 'app_content_maxwidth',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'acfe_permissions' => '',
			'default_value' => 960,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 728,
			'max' => 1280,
			'step' => 1,
		),
		array(
			'key' => 'field_5e272264a65a4',
			'label' => 'App Header Color',
			'name' => 'app_header_color',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'choices' => array(
				'appHeader' => 'Default',
				'appHeader no-border' => 'Default - No Border',
				'appHeader bg-primary text-light' => 'Primary',
				'appHeader bg-info text-light' => 'Info',
				'appHeader bg-light' => 'Light',
				'appHeader bg-dark text-light' => 'Dark',
			),
			'allow_null' => 0,
			'default_value' => 'appBottomMenu',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e27204d14e5d',
			'label' => 'App Bottom Menu Color',
			'name' => 'app_bottom_menu_color',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'choices' => array(
				'appBottomMenu' => 'Default',
				'appBottomMenu no-border' => 'Default - No Border',
				'appBottomMenu bg-primary text-light' => 'Primary',
				'appBottomMenu bg-info text-light' => 'Info',
				'appBottomMenu bg-light' => 'Light',
				'appBottomMenu bg-dark text-light' => 'Dark',
			),
			'allow_null' => 0,
			'default_value' => 'appBottomMenu',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e2ac704dabcf',
			'label' => 'App Sidebar Color',
			'name' => 'app_sidebar_color',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'acfe_permissions' => '',
			'choices' => array(
				'modal-content' => 'Default',
				'bg-primary' => 'Primary',
				'bg-info' => 'Info',
				'bg-dark' => 'Dark',
			),
			'allow_null' => 0,
			'default_value' => 'modal-content',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e2ae62c4d638',
			'label' => 'App Action Button',
			'name' => 'app-action-button',
			'type' => 'true_false',
			'instructions' => 'This activates the action button, visible only to logged in users',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_admin' => 0,
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'app-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1579883054,
));

endif;